Lesson 1
4itosik/react_blog pull request #1
Opened 2017-05-25 10:01 UTC by 4itosik

2017-05-25 13:50 UTC, index01d requested changes
Нужно внести незначительные коррективы

2017-05-25 13:50 UTC, index01d commented on components/ui/BlogItem.js
> +    React.createElement(Image, {src: props.src, width: 100, width: 100, alt: "foo"}),
дубль width

2017-05-25 13:50 UTC, index01d commented on components/ui/BlogItem.js
> +    React.createElement(Image, {src: props.src, width: 100, width: 100, alt: "foo"}),
возможно лучше хранить настройки высоты и ширины картинки, как и alt также в исходном объекте

2017-05-25 13:50 UTC, index01d commented on components/containers/BlogPage.js
> +    src: "https://lh3.googleusercontent.com/nYhPnY2I-e9rpqnid9u9aAODz4C04OycEGxqHG5vxFnA35OGmLMrrUmhM9eaHKJ7liB-=w300"
имеет смысл завернуть src под ключ image и добавить туда же информацию про высоту, ширину, alt картинки

2017-05-25 13:50 UTC, index01d commented on components/ui/BlogItem.js
> +    React.createElement(Image, {src: props.src, width: 100, width: 100, alt: "foo"}),
даже в случае приведения картинки к нужному размеру информация в исходном объекте будет полезна для правильной обработки пропорций блока

2017-05-25 13:50 UTC, index01d commented on components/ui/BlogList.js
> +        (post, key) => (
в качестве ключа key, лучше использовать уникальный идентификатор post.id (предварительно завести его в исходном объекте), тогда при перерисовке react не будет считать блоки с одинаковыми ключами, но разными постами одним и тем же элементом (содержимое элементов не будет "скакать")

2017-05-25 13:50 UTC, index01d commented on components/ui/BlogList.js
> +          React.createElement(BlogItem, { text: post.text, src: post.src, key: key })
название src не совсем точно описывает содержимое и вообще лучше передавать всю запись (деструктурирование выглядит неуместным, тк компонент BlogItem как раз отвечает за отображение всей записи)

2017-05-25 13:50 UTC, index01d commented on components/ui/Image.js
> +    { src: src, width: width, height: height, alt: alt }
можно просто `{ src, width, height, alt }` (сокращенно)

2017-05-26 07:55 UTC, 4itosik commented on components/ui/BlogItem.js
> +    React.createElement(Image, {src: props.src, width: 100, width: 100, alt: "foo"}),
Исправил, правда не уверен правильно ли я понял
`даже в случае приведения картинки к нужному размеру информация в исходном объекте будет полезна для правильной обработки пропорций блока`

2017-05-26 08:09 UTC, index01d approved these changes

2017-05-26 08:12 UTC, merged