Lesson5
4itosik/react_blog pull request #5
Opened 2017-06-26 13:37 UTC by 4itosik

2017-06-26 13:37 UTC, 4itosik commented
Есть некоторые упущенные моменты, не обновляется url при клике по пагинации или поиске через форму

2017-06-28 05:16 UTC, index01d requested changes

2017-06-28 05:16 UTC, index01d commented on src/App.js
> +import Routers from 'routes/index';
можно просто from 'routes'

2017-06-28 05:16 UTC, index01d commented on src/routes/index.js
> +    <Route exact path='/about' component={About}/>
ссылку на about желательно также подшить в хелпер

2017-06-28 05:16 UTC, index01d commented on src/components/containers/BlogPage.js
> +            handlePagination={this.handlePagination} items={this.state.countPages}
`items={this.state.countPages}` звучит не слишком логично, лучше свойство переименовать

2017-06-28 05:16 UTC, index01d commented on src/components/containers/BlogPage.js
> +    this.fetachPosts();
fetach?

2017-06-28 05:16 UTC, index01d commented on src/components/containers/BlogPage.js
> +    this.state = { posts: [], renderPosts: [], currentPage: 1, per: 3, countPages: 0 };
нарушение условий использования состояния. Количество страниц можно посчитать из количества постов и количества записей на страницу. Поэтому его лучше рассчитать в презентационном компоненте пейджинации из свойств. Заодно не придется дублировать в двух функциях Math.ceil при расчете

2017-06-28 05:16 UTC, index01d commented on src/components/containers/BlogPage.js
> +        const posts = res.body;
нет проверки на err, но это пока необязательно (зато обязательно в production)

2017-06-28 05:16 UTC, index01d commented on src/components/containers/BlogPage.js
> +    const renderPosts = this.preparePostForPagination(searchPosts, currentPage);
вот такое дублирование с кэшированием выглядит лишним. можно прямо на месте сделать slice или написать функцию

```
const getPaginatedPosts() // параметры не нужны, тк они есть в состоянии
```

которая вернет slice без клонирования. И использовать ее в месте, где нужно получить подмножество записей. Операция slice в данном кейсе не слишком затратная.

Дублировать в состоянии записи не слишком хорошее дело.

2017-06-28 05:16 UTC, index01d commented on src/components/containers/Post.js
> +    this.fetachPost();
fetach распространяется по всему коду:)

2017-06-28 05:16 UTC, index01d commented on src/components/ui/Like.jsx
>  const Like = ({postId, count, incrementLikeCount}) => (
лучше избегать кастомных названий и называть коллбэк попроще, onClick

2017-06-28 13:09 UTC, 4itosik commented on src/components/containers/BlogPage.js
> +    this.state = { posts: [], renderPosts: [], currentPage: 1, per: 3, countPages: 0 };
Перенес `countPages` в компонент `Pagination`, но есть момент, теперь при инициализации `posts` пустой, когда срабатывает `componentDidMount` и в `fetchPosts` меняется состояние, почему то не происходит перерендер компонента `Pagination`, мб я что то упустил из части про жизненный цикл приложения?

2017-06-28 13:12 UTC, 4itosik commented on src/components/containers/BlogPage.js
> +    const renderPosts = this.preparePostForPagination(searchPosts, currentPage);
Вот тут не понял, 
предложение вообще убрать `renderPosts` из состояния? 

во всех местах кроме данного (`handleSearchForm`) я могу при вызове `<BlogList posts={this.state.renderPosts} incrementLikeCount={this.incrementLikeCount} />` заменить `this.state.renderPosts` на `getPaginatedPosts()`, однако в случае с `handleSearchForm` надо будет каждый раз с API получать список постов или вообще эту логику переложить на сервер API.

2017-06-28 17:58 UTC, index01d commented on src/components/containers/BlogPage.js
> +    const renderPosts = this.preparePostForPagination(searchPosts, currentPage);
> предложение вообще убрать renderPosts из состояния?

так точно

> вообще эту логику переложить на сервер API.

поидее в продакшене так и будет всегда (и пейджинация и поиск будут оставаться на сервере)

2017-06-29 08:34 UTC, 4itosik commented
Все исправил, но есть еще 1 вопрос, как зарефакторить и убрать дублирование 
https://github.com/4itosik/react_blog/blob/0e73ecc8be1e4c5309fcca08d75d4a0fae8d35d1/src/components/containers/BlogPage.js#L28-L36 - здесь и https://github.com/4itosik/react_blog/blob/0e73ecc8be1e4c5309fcca08d75d4a0fae8d35d1/src/components/containers/BlogPage.js#L57-L67 

я пытался написать функцию, которая делает только запрос и возвращает результат, но не делал , функция всегда возвращает `undefined`

2017-06-30 18:57 UTC, index01d commented
> я пытался написать функцию, которая делает только запрос и возвращает результат, но не делал , функция всегда возвращает undefined

Подход в корне неправильный, тк асинхронные процессы нужно реализовывать асинхронно и лучше в реактивной парадигме. Можно написать функцию которая будет выполнять callback по факту выполнения:

```
const fetchRequest = () => (
  request.get(
      APIBaseUrl,
      {},
      (err, res) => callback(res)
  ) 
)
```

и вызывать ее как `fetchPost((res) => { // некая логика })`

2017-06-30 18:59 UTC, index01d approved these changes

2017-07-01 15:25 UTC, merged