Lesson6
4itosik/react_blog pull request #6
Opened 2017-07-06 10:16 UTC by 4itosik

2017-07-09 09:43 UTC, blackleadsu requested changes
Обязательно:
- исправить замечания в комментариях
- убрать warning'и из консоли
- убрать логику и побочные эффекты из `actions` в `reducers`. В `actions` логики быть не должно.
- сделать так, чтобы лайки работали: сейчас они сбрасываются при переходе со страницы на страницу. Для этого стоит сделать контейнер для Like, добавить дополнительную логику в reducer'ы поста и списка постов. Можешь "гонять" лайки через сервер (добавить запрос на инкремент и сохранять), а можешь сохранять в состоянии приложения -- на твой выбор. 

Рекомендации:
- я написал про папку views. Ты можешь, чтобы ui не разрастался, сделать во views подпапки (согласно представлениям), и разместить в них те ui-компоненты, которые используются только в этом view. Общие многократно используемые останутся в ui.
- то же самое справедливо для layout. Твои footer и header используются только в лэйауте, почему бы не расположить рядом? Кстати, если ты делаешь из `components/layouts/MainLayout.js` => `components/layouts/MainLayout/index.js` импорты не поменяются: `import MainLayout from 'components/layouts/MainLayout';`. А в папке можно разместить ui элементы. То же самое для views. 
- круто если свяжешь работу пагинации и поиска со строкой url. Чтобы переключение страницы и поисковый запрос отбражались там, чтобы корректно забирались оттуда при переходе по прямой ссылке (например, на вторую страницу и/или на результат поиска).

2017-07-09 09:43 UTC, blackleaden commented on src/containers/BlogListContainer.js
> +const likeClick = (postId) => ({
Ты описываешь actionCreator для в контейнере; нужно вынести в actions и избавиться от дублирования.

2017-07-09 09:43 UTC, blackleaden commented on src/actions/Posts.js
> +  if (foundText) {
Эта логика должна быть в reducer'е

2017-07-09 09:43 UTC, blackleaden commented on src/components/containers/BlogPage.js
> -import React from 'react';
Папка называется `components/containers`, но содержимое не является контейнерами. Логично назвать это `views`.

2017-07-09 09:43 UTC, blackleaden commented on src/components/containers/Post.js
> +  post: React.PropTypes.shape({
Эти PropTypes соответствуют действительности?

2017-07-09 09:43 UTC, blackleaden commented on src/components/containers/BlogPage.js
> +  const getPaginatedPosts = () => {
Контейнерная логика в презентационном компоненте -- уносить выше.

2017-07-09 09:51 UTC, blackleaden commented on src/containers/SearchFormContainer.js
> +export default connect(stateToProps, actionToProps)(SearchForm);
connect не принимает объект. Можно пустую анонимную функцию прямо здесь, `export default connect(()=>({}), actionToProps)(SearchForm);`, а еще лучше -- identity из lodash (не создаешь функцию).

2017-07-11 18:40 UTC, 4itosik commented
все поправил, кроме пагинацию и поиска в url, хочу сделать это, но вообще ни в какую не получается.
@blackleaden, подтолкнешь в нужном направлении?

2017-07-11 19:05 UTC, 4itosik commented
В данной реализации, строка url меняется, но выполняется заново запрос к API на получение всех постов, 
также не смог решить с дублирование при лайках постов ( так как в одном случае нам надо обновить 1 пост на странице, а в другом вернуть обновленную коллекцию постов )

2017-07-13 12:41 UTC, blackleadsu approved these changes
Дублирование с лайками -- нормально.
Со строкой поиска рекомендую сделать так:
сама строка только производит переход на нужный url, а вытягивание нужных данных происходит в роуте, который нужно будет параметризовать соответствующим образом. Точно также можно реализовать пагинацию, работающую через url.

2017-07-17 06:57 UTC, merged